"""Audio Analyzer module for Deep Audit Knowledge Engine."""
from datetime import datetime
from core.prompt_loader import render_prompt
from config import generate_with_media_retry

def analyze_audio(title: str, file_path: str, mime_type: str = "audio/mpeg", tags: str = "") -> str:
    """Analyze a local audio file using Gemini 2.0 native audio support.
    
    Args:
        title (str): The user-provided title for the audio.
        file_path (str): Absolute path to the temporary audio file.
        mime_type (str): MIME type of the audio (e.g., audio/mpeg, audio/wav).
        tags (str): Additional tags.
        
    Returns:
        str: Markdown generated by Gemini.
    """
    
    # 1. Prepare prompt
    context = {
        "title": title,
        "source_url": "Archivo Local",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "tags": tags
    }
    
    final_prompt = render_prompt("audio_analysis.md", context)
    
    # 2. Call Gemini with the media file
    result = generate_with_media_retry(final_prompt, file_path, mime_type=mime_type)
    
    return result
